
project_id = "mhaeypkujysazwnfupml"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

# Edge Functions configuration
[functions.send-invitation]
verify_jwt = true
