// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhaeypkujysazwnfupml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oYWV5cGt1anlzYXp3bmZ1cG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDg0MTIsImV4cCI6MjA1OTUyNDQxMn0.eOESntiC_sI53-erT0pZpUimhkxM7Qh1v5BqyFXuPrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);